modelVersion=4.0.0

org.gradle.jvmargs=-Xmx4096M
groupId=org.springframework.samples.service.service
artifactId=ms-cross-cost-center
version=1.0.0.SNAPSHOT

packaging=jar

springDataCommonsVersion=2.1.9.RELEASE

hsqldbVersion=2.3.4

apiContextPath=/api


#Início

#Até então não precisa gerecionar a versão assim
#Impacta no gerenciamento automático do gradle
springBootVersion=3.4.4
