# spring.profiles.active=local

app.name=CostCenterMsApp

### SPRING BOOT WEB : EMBEDDED SERVER
server.port = 9000

### LOGGING
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n

### DATABASE : ORACLE
spring.datasource.url=jdbc:oracle:thin:@dev-oradb-scan.valecard.com.br:1521/VALEDEV
spring.datasource.username=adeb
spring.datasource.password=valedev
spring.datasource.driver-class=oracle.jdbc.driver.OracleDriver

### JPA - QUERY TRACE
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.jdbc.core.JdbcTemplate=DEBUG
logging.level.org.springframework.jdbc.core.StatementCreatorUtils=TRACE

### HIKARI POOL - TRACE
logging.level.com.zaxxer.hikari.pool.HikariPool=DEBUG
logging.level.com.zaxxer.hikari.HikariConfig=DEBUG

logging.level.org.springframework.beans.factory.support=DEBUG

### Gerenciamento de logs
url.producer.kafka=http://gerenciamento-log-producer-dev.valecard.com.br/kafka/publish?topic=gerenciamento-log&key=from-ms-cost-center

spring.cloud.vault.token=s.kHv7DdaDXVbmcONUSl3rhdYA